depends:
    - test-runner
    - serializer

tests:
    - tests/can_datagram_tests.cpp
    - tests/datagrams_command_tests.cpp
    - tests/mocks/flash_writer_mock.cpp
    - tests/mocks/can_interface_mock.cpp
    - tests/config_tests.cpp
    - tests/flash_command_tests.cpp
    - tests/config_commands_tests.cpp

source:
    - can_datagram.c
    - command.c
    - config.c

