depends:
    - test-runner
    - serializer
    - crc

tests:
    - tests/can_datagram_tests.cpp
    - tests/mocks/flash_writer_mock.cpp
    - tests/mocks/can_interface_mock.cpp
    - tests/mocks/boot_arg.cpp
    - tests/config_tests.cpp
    - tests/flash_command_tests.cpp
    - tests/config_commands_tests.cpp
    - tests/datagrams_command_tests.cpp
    - tests/integration_tests.cpp
    - tests/mocks/memory_mock.c

source:
    - can_datagram.c
    - command.c
    - config.c

target.arm:
    - flash_writer_stm32f3.c
    - boot_arg.c
    - boot.s
