depends:
    - test-runner
    - serializer

tests:
    - tests/can_datagram_tests.cpp
    - tests/datagrams_command_tests.cpp
    - tests/mocks/flash_writer_mock.cpp

source:
    - can_datagram.c
    - command.c

